module.exports = {
  BTN_TEXTS: {
    MENU: 'Menu',
    MAIN_MENU_WHATSON: '🎤 What’s on now',
    MAIN_MENU_SCHEDULE: '🕐 Schedule',
    MAIN_MENU_ASK: '❔Ask questions to the speaker',
    MAIN_MENU_INFO: 'ℹ️ Information',
    MAIN_MENU_EMERGENCY: '🆘️ Emergency',
    WHATSON_SCHEDULE_DAY1: 'Day One Schedule',
    WHATSON_SCHEDULE_DAY2: 'Day Two Schedule',
    SCHEDULE_DAY1: '⏪ Day One - May 24th',
    SCHEDULE_DAY2: '⏩ Day Two - May 25th',
    BACK_TO_MAIN: 'Back to main menu',
    INFO_CONTACT_ORGS: '🗨 Contact us',
    INFO_LOCATION: '📌 Conference location',
    INFO_WORKSHOPS: '📚 Workshops',
    INFO_PARTIES: '🎉 Walking tour and parties',
    INFO_BACK_TO_INFO: 'Back to information',

    MAIN_MENU_ADMIN: '--- Administration ---',
    ADMIN_REFRESH_APP: '--- Refresh application ---',
    ADMIN_SEND_NOTIFICATION: '--- Send notification to all users ---',
    ADMIN_APPROVE: 'Ok, let\'s do it! Approve',
    ADMIN_DECLINE: 'No, sorry, I\'ve made a mistake. Decline',
  },
  BTN_DATA: {
    MAIN_MENU_WHATSON: 'MAIN_MENU_WHATSON',
    MAIN_MENU_SCHEDULE: 'MAIN_MENU_SCHEDULE',
    MAIN_MENU_ASK: 'MAIN_MENU_ASK',
    MAIN_MENU_INFO: 'MAIN_MENU_INFO',
    MAIN_MENU_EMERGENCY: 'MAIN_MENU_EMERGENCY',
    SCHEDULE_DAY1: 'SCHEDULE_DAY1',
    SCHEDULE_DAY2: 'SCHEDULE_DAY2',
    BACK_TO_MAIN: 'BACK_TO_MAIN',
    INFO_CONTACT_ORGS: 'INFO_CONTACT_ORGS',
    INFO_LOCATION: 'INFO_LOCATION',
    INFO_WORKSHOPS: 'INFO_WORKSHOPS',
    INFO_PARTIES: 'INFO_PARTIES',
    INFO_BACK_TO_INFO: 'INFO_BACK_TO_INFO',

    MAIN_MENU_ADMIN: 'MAIN_MENU_ADMIN',
    ADMIN_REFRESH_APP: 'ADMIN_REFRESH_APP',
    ADMIN_SEND_NOTIFICATION: 'ADMIN_SEND_NOTIFICATION',
    ADMIN_SEND_NOTIFICATION_APPROVE: 'ADMIN_SEND_NOTIFICATION_APPROVE',
    ADMIN_SEND_NOTIFICATION_DECLINE: 'ADMIN_SEND_NOTIFICATION_DECLINE'
  },
};
